web:
  container_name: web
  build: .
  ports:
   - "3000:3000"
   - "35729:35729"
  volumes:
   - ./app:/home/mean/app
  environment: 
   NODE_ENV: development
db:
  container_name: db
  image: mongo:latest
  ports: 
   - "27017:27017"
