web:
  container_name: web
  build: .
  net: ${DOCKER_NETWORK_NAME}
  ports:
   - "3000:3000"
   - "35729:35729"
  environment: 
   NODE_ENV: development
   DB_1_PORT_27017_TCP_ADDR: db
db:
  container_name: db
  net: ${DOCKER_NETWORK_NAME}
  image: mongo:latest
  ports: 
   - "27017:27017"
